/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/GMMKCRoJXHX
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Sheet, SheetTrigger, SheetContent } from "@/components/ui/sheet";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar";
import {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
} from "@/components/ui/card";

export function Main() {
  return (
    <div className="flex flex-col min-h-screen bg-[#f5f5f5]">
      <header className="flex items-center justify-between bg-[#ffffff] px-4 py-3 shadow-sm sm:px-6">
        <Sheet>
          <SheetTrigger asChild>
            <Button variant="ghost" size="icon" className="rounded-full">
              <MenuIcon className="h-6 w-6" />
              <span className="sr-only">Toggle navigation menu</span>
            </Button>
          </SheetTrigger>
          <SheetContent side="left" className="sm:max-w-xs">
            <nav className="grid gap-4 p-4 text-lg font-medium">
              <Link
                href="#"
                className="flex items-center gap-2 hover:scale-105 transition-transform"
                prefetch={false}
              >
                <Package2Icon className="h-6 w-6" />
                <span>Grievance Reporting</span>
              </Link>
              <Link
                href="#"
                className="flex items-center gap-2 hover:scale-105 transition-transform"
                prefetch={false}
              >
                <ListIcon className="h-6 w-6" />
                <span>Manage Requests</span>
              </Link>
              <Link
                href="#"
                className="flex items-center gap-2 hover:scale-105 transition-transform"
                prefetch={false}
              >
                <PlusIcon className="h-6 w-6" />
                <span>Add Request</span>
              </Link>
              <Link
                href="#"
                className="flex items-center gap-2 hover:scale-105 transition-transform"
                prefetch={false}
              >
                <UserIcon className="h-6 w-6" />
                <span>Edit Profile</span>
              </Link>
              <Link
                href="#"
                className="flex items-center gap-2 hover:scale-105 transition-transform"
                prefetch={false}
              >
                <InfoIcon className="h-6 w-6" />
                <span>About Us</span>
              </Link>
              <Link
                href="#"
                className="flex items-center gap-2 hover:scale-105 transition-transform"
                prefetch={false}
              >
                <MailIcon className="h-6 w-6" />
                <span>Contact Us</span>
              </Link>
              <Link
                href="#"
                className="flex items-center gap-2 hover:scale-105 transition-transform"
                prefetch={false}
              >
                <BugIcon className="h-6 w-6" />
                <span>FAQs</span>
              </Link>
              <Link
                href="#"
                className="flex items-center gap-2 hover:scale-105 transition-transform"
                prefetch={false}
              >
                <BookIcon className="h-6 w-6" />
                <span>Resources</span>
              </Link>
            </nav>
          </SheetContent>
        </Sheet>
        <div className="flex-1 flex justify-center">
          <Link
            href="#"
            className="flex items-center gap-2 font-semibold"
            prefetch={false}
          >
            <Package2Icon className="h-6 w-6" />
            <span>IssueInbox</span>
          </Link>
        </div>
        <div className="flex items-center gap-4">
          <Link
            href="#"
            className="rounded-full hover:scale-105 transition-transform"
            prefetch={false}
          >
            <Avatar className="h-8 w-8">
              <AvatarImage src="/placeholder-user.jpg" alt="Avatar" />
              <AvatarFallback>JD</AvatarFallback>
            </Avatar>
          </Link>
        </div>
      </header>
      <main className="flex-1 bg-[#f5f5f5]">
        <div className="container mx-auto py-8 px-4 sm:px-6 md:py-12 lg:px-8">
          <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-3">
            <Card className="hover:scale-105 transition-transform">
              <CardHeader>
                <CardTitle>Manage Requests</CardTitle>
                <CardDescription>
                  View, update, and resolve grievance requests.
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-2">
                  <p>
                    Track the status of your grievance requests and take
                    appropriate actions.
                  </p>
                  <Button href="/requests">Go to Requests</Button>
                </div>
              </CardContent>
            </Card>
            <Card className="hover:scale-105 transition-transform">
              <CardHeader>
                <CardTitle>Add Request</CardTitle>
                <CardDescription>
                  Submit a new grievance request for review.
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-2">
                  <p>
                    Fill out the form to create a new grievance request and
                    submit it for processing.
                  </p>
                  <Button href="/new-request">Create Request</Button>
                </div>
              </CardContent>
            </Card>
            <Card className="hover:scale-105 transition-transform">
              <CardHeader>
                <CardTitle>Edit Profile</CardTitle>
                <CardDescription>
                  Update your personal information and preferences.
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-2">
                  <p>
                    Manage your profile settings, including contact information
                    and notification preferences.
                  </p>
                  <Button href="/profile">Go to Profile</Button>
                </div>
              </CardContent>
            </Card>
            <Card className="hover:scale-105 transition-transform">
              <CardHeader>
                <CardTitle>FAQs</CardTitle>
                <CardDescription>
                  Find answers to common questions about the grievance reporting
                  process.
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-2">
                  <p>
                    Browse our frequently asked questions to get the information
                    you need.
                  </p>
                  <Button href="/faq">View FAQs</Button>
                </div>
              </CardContent>
            </Card>
            <Card className="hover:scale-105 transition-transform">
              <CardHeader>
                <CardTitle>Resources</CardTitle>
                <CardDescription>
                  Explore helpful guides and information to assist with your
                  grievance.
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-2">
                  <p>
                    Access our library of resources to learn more about the
                    grievance reporting process.
                  </p>
                  <Button href="/resources">View Resources</Button>
                </div>
              </CardContent>
            </Card>
            <Card className="hover:scale-105 transition-transform">
              <CardHeader>
                <CardTitle>Contact Us</CardTitle>
                <CardDescription>
                  Get in touch with our team for assistance or additional
                  information.
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-2">
                  <p>
                    If you have any questions or need help, don't hesitate to
                    reach out to us.
                  </p>
                  <Button href="/contact">Contact Us</Button>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </main>
      <footer className="bg-[#333333] py-4 text-white">
        <div className="container mx-auto px-4 sm:px-6 md:flex md:items-center md:justify-between lg:px-8">
          <p className="text-center text-sm md:text-left">
            &copy; 2023 Grievance Reporting. All rights reserved.
          </p>
          <div className="mt-4 flex justify-center gap-4 md:mt-0">
            <Link
              href="#"
              className="text-white hover:text-gray-300"
              prefetch={false}
            >
              Privacy Policy
            </Link>
            <Link
              href="#"
              className="text-white hover:text-gray-300"
              prefetch={false}
            >
              Terms of Service
            </Link>
          </div>
        </div>
      </footer>
    </div>
  );
}

function BookIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20" />
    </svg>
  );
}

function BugIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 2 1.88 1.88" />
      <path d="M14.12 3.88 16 2" />
      <path d="M9 7.13v-1a3.003 3.003 0 1 1 6 0v1" />
      <path d="M12 20c-3.3 0-6-2.7-6-6v-3a4 4 0 0 1 4-4h4a4 4 0 0 1 4 4v3c0 3.3-2.7 6-6 6" />
      <path d="M12 20v-9" />
      <path d="M6.53 9C4.6 8.8 3 7.1 3 5" />
      <path d="M6 13H2" />
      <path d="M3 21c0-2.1 1.7-3.9 3.8-4" />
      <path d="M20.97 5c0 2.1-1.6 3.8-3.5 4" />
      <path d="M22 13h-4" />
      <path d="M17.2 17c2.1.1 3.8 1.9 3.8 4" />
    </svg>
  );
}

function InfoIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M12 16v-4" />
      <path d="M12 8h.01" />
    </svg>
  );
}

function ListIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="8" x2="21" y1="6" y2="6" />
      <line x1="8" x2="21" y1="12" y2="12" />
      <line x1="8" x2="21" y1="18" y2="18" />
      <line x1="3" x2="3.01" y1="6" y2="6" />
      <line x1="3" x2="3.01" y1="12" y2="12" />
      <line x1="3" x2="3.01" y1="18" y2="18" />
    </svg>
  );
}

function MailIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </svg>
  );
}

function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  );
}

function Package2Icon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 9h18v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9Z" />
      <path d="m3 9 2.45-4.9A2 2 0 0 1 7.24 3h9.52a2 2 0 0 1 1.8 1.1L21 9" />
      <path d="M12 3v6" />
    </svg>
  );
}

function PlusIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  );
}

function UserIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  );
}
